### ISSUE TITLE
installation homebridge-magic-blue-bulb raspberry

### ISSUE THREAD

**Issue by fraraf85** [lucavb/homebridge-magic-blue-bulb#1]
hello you can kindly help to install the plugin of raspberry?

**Comment by lucavb** [comment]
could you elaborate more on what is unclear about the README I provided?

**Comment by fraraf85** [comment]
how do I install the plugin since it is not registered on npm?

**Comment by lucavb** [comment]
I have updated the README with a reference to my other project regarding the installation of plugins outside of npm.

**Comment by fraraf85** [comment]
Also by running the following command, does not recognize the plugin, how do I fix?

**Comment by lucavb** [comment]
What command are you talking about?

**Comment by fraraf85** [comment]
[2017-03-07 14:38:55] ====================
[2017-03-07 14:38:55] ERROR LOADING PLUGIN homebridge-magic-blue-bulb:
[2017-03-07 14:38:55] Error: Cannot find module 'noble'
    at Function.Module._resolveFilename (module.js:469:15)
    at Function.Module._load (module.js:417:25)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/home/osmc/.homebridge/plugin/homebridge-magic-blue-bulb/index.js:4:13)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)

**Comment by lucavb** [comment]
run `npm i` inside the folder where you downloaded the plugin. you are missing the noble dependency.

**Comment by fraraf85** [comment]
in Homebridge folder or where I put magic-blue-bulb?

**Comment by lucavb** [comment]
well the director where you cloned this repository to. if you followed this guide this is most likely going to be `/var/homebridge/other_plugins/homebridge-magic-blue-bulb/`

**Comment by fraraf85** [comment]
npm I gave no results, I managed manually installing noble, it is now recognized the plugin. I wanted to ask if you first have to associate the light bulb to the raspberry and then use it with Homebridge, or happens all automatically?

**Comment by lucavb** [comment]
there is no pairing process. it should work with just the Mac address and considering that the bulb is not already connected to any other device

**Comment by fraraf85** [comment]
I've done everything correctly, only that the bulb does not respond you command

**Comment by lucavb** [comment]
Consider the original post, that discovered the codes for the bulbs. Read through it, especially the part where he uses gatttool to test his codes. Make sure those work for you. There is the possibility that you are having a different version that utilises a different handle.
