### ISSUE TITLE
More than 1 bulb. 

### ISSUE THREAD

**Issue by daniel4099** [lucavb/homebridge-magic-blue-bulb#6]
Can I add more than I bulb ?

**Comment by lucavb** [comment]
Yes, just add the example config multiple times.

**Comment by daniel4099** [comment]
Thank I have 2 of them now but I have problem with one bulb the color change is wrong. It almost always purple. I 've tried with handle 46 but then it's not able to connect I'm using configuration without handle. One of the bulb works fine but the second one has wrong color palet.

**Comment by daniel4099** [comment]
Anyone can help with the color palet issue ?

**Comment by lucavb** [comment]
First of all, I'd like you to open another issue, because this issue with this title is obviously answered. But to answer your question, I am not aware of any other handle number aside from 11, 12 and 46. Sorry about that.
