### ISSUE TITLE
I made a version of this compatible with Triones RGB LED BLE devices

### ISSUE THREAD

**Issue by v0r73x** [lucavb/homebridge-magic-blue-bulb#8]
Hi Lukas,

I modified your plugin with full Triones support in Homekit. Since I am security network engineer and haven't so deep knowledge of coding i modified the code to be compatible with Triones devices like these: 

https://www.amazon.de/iLC-Strahler-Telefon-APP-Steuerung-million/dp/B07RL74CF9/ref=pd_lpo_201_t_2/257-6528870-5212838?_encoding=UTF8&pd_rd_i=B07RL74CF9&pd_rd_r=2573d4b3-935f-4fa2-b714-cf09e5d090db&pd_rd_w=VlB8G&pd_rd_wg=xPeYO&pf_rd_p=d5c9797d-0238-4119-b220-af4cc3420918&pf_rd_r=3MGKPB6HECPEZFTF9X87&psc=1&refRID=3MGKPB6HECPEZFTF9X87 

Hope that is ok?  I sill use it for private purposes. If I have the OK of you I will upload this plugin to github to make it usable for all who want to use it. Thanks for the basic idea with noble and best wishes for XMAS and happy new year :)

**Comment by lucavb** [comment]
Hey,

of course this is okay if you extend or modify the project. The only requirement I would have is that it then also becomes licensed under GPLv3 as this project(, since that is how the GPL works). If you need any help, feel free to ask :) 

Hope you had a nice Christmas and a happy new year to you.

Cheers.

**Comment by v0r73x** [comment]
hey Lukas,

checked out your cleaned up version 1.0.3 - with prettier.
It loads much faster the state in homekit as far I can reproduce it ;) 

Only problemI have everytime is that in node 14 i cannot install from scratch since it uses the noble orgiginal version - with reconfigure the package and index.js i can get it run with abadonware noble. could be nice that you implement it directly into your version 1.0.3 what should help the user who will use it with actual node install on a rpi for example.

your version 2 look also nice from code perspective but all what I tried will not get it run... I saw it uses already abadoneware noble but it will produce js exceptions... just for you as feedback from user side ;) 

happy new year and looking forward to hear from you. 
BTW: if its possible you can add the part of code for triones as well into your plugin - or i will make one from yours (but therefore it could be nice if you can help me since i never published in github until now ;) )
 - its just the write buffer which must be changed - could be also a good way to export it to config.js so that more than only our bluetooth rgb bulbs will be useable - what do yo think ?

**Comment by lucavb** [comment]
Hang on I am a bit lost, what you want to do. If all that needs to be changed is the buffer, then I guess we could make that configurable and merge it. Can you post the difference here? Ideally by showing the current bytes that are being transmitted and then the new set. 

Also, am I understanding you correctly that you want to have a version based on the old code base but with @abandonware/noble? 

Regarding version 2.0.0, can you share the errors you received?

Thanks in advance.

**Comment by el** [comment]
Hey @v0r73x

 Can you make that available if that's ok with you and @lucavb ?

**Comment by v0r73x** [comment]
hi lucas,
sorry for the late reply - had to organise real world topics XD

**Comment by v0r73x** [comment]
so, first - jest i cannot get run original noble on buster in a flawless way (with nodejs upper than 12.XX) so i managed to change your code to use abadoneware noble - its jsut a few clicks to get it run - i can send you the instruction what i must change to get it run - but in total i faced (now after testing more than a month successfully) that i cannot run the warm white option when i go in the middle of the color wheel - i guess that could be work because i saw equal code in magichome js plugin.. it could be that, if we have a face2face communication that can solve the issue - again, i am not a coder - just a good skilled script kiddy  ;) 

to haven't the situation that after installing your plugin i have to modify the code manually i suggest to implement, if its triones devices a script snipped to choose this device. Or a better idea is to implement a array which parses the information out of the config.json to make it possible to use it for universal device ... otherwise i like to use your code, my mod, and to improve my mod to run with real warm white option which is provides by device - its more than twiche that bright then the rgb led. since i not reasselmbled the device i just can guess if its a rgb+ww setup on the Fluter 

if i should make a fork of it; let me know how to do it without getting issues regarding gpl or gnu or your privacy content of you ;) . and the best will be to get ww work with the script

**Comment by lucavb** [comment]
I would suggest that you create a PR against this repository. You can fork it, commit your changes there and then make the PR and then we can discuss this. The alternative would be that you can of course fork this repository and then release your changes separately on npmjs.com. The only requirement license-wise here is that you will have to release your code under the GPLv3 (or another compatible) license.

**Comment by v0r73x** [comment]
i made hopefully correct, my changes into a new created fork - please assist if sth. was going wrong because i cannot discover it in homebridge plugins

**Comment by v0r73x** [comment]
Hi Lucas,

need your help with my fork - I cannot find it in plugins on homebridge - i guess i done sth. wrong here ... if possible we can chat face2face if you let me know how i can contact you 

thx,

Rob

**Comment by SlyRix** [comment]
hi can i have your triones-homebridge-plugin pls ?

**Comment by douginoz** [comment]
@v0r73x You haven't published your version over on https://www.npmjs.com, so it can't be installed.   If you publish it there, we can install it via "npm install -g homebridge-magic-blue-bulb-v0r73x".

**Comment by v0r73x** [comment]
Thx for this Feedback - this is now published as magic-triones on npmjs

Thanks for  the help and the idea of Luca ;-)
